#!/bin/bash
. .var


if [ -z $1 ]; then
  echo "Missing argument. ./domain_block <domain>"
  exit 1
fi
DOMAIN=$1

curl \
  -X DELETE \
  -d "domain=${DOMAIN}" \
  --header "Authorization: Bearer ${MASTODON_ACCESS_TOKEN}" \
  -sS \
  https://${MASTODON_SERVER}/api/v1/domain_blocks