#!/usr/bin/env sh
BASEDIR=$(dirname "$0")

sh $BASEDIR/_var.sh

if [ -z $1 ]; then
  echo "Missing argument. domain_unblock <domain>"
  exit 1
fi
DOMAIN=$1

curl \
  -w "\n" \
  -X DELETE \
  -d "domain=${DOMAIN}" \
  --header "Authorization: Bearer ${MASTODON_ACCESS_TOKEN}" \
  -sS \
  https://${MASTODON_SERVER}/api/v1/domain_blocks