#!/bin/sh
. .var

# Attempt to get the token from oauth authorize/token scheme
# Difficult to get the redirection to work in CLI, might as well get it from settings for now

authorization_code=curl \
  -X GET \
  -d "response_type=code" \
  -d "client_id=${MASTODON_CLIENT_KEY}" \
  -d "redirect_uri=${MASTODON_REDIRECT_URI}" \
  -d "scope=read write follow admin:read admin:write" \
  -d "force_login=true" \
  -sSL \
  https://${MASTODON_SERVER}/oauth/authorize

# /TODO push user credentials to website then get returned authorization_code (next command needs to be updated accordingly)

MASTODON_ACCESS_TOKEN=curl \
  -X POST \
  -d "grant_type=code" \
  -d "client_id=${MASTODON_CLIENT_KEY}" \
  -d "client_secret=${MASTODON_CLIENT_SECRET}" \
  -d "redirect_uri=${MASTODON_REDIRECT_URI}" \
  -d "scope=read write follow admin:read admin:write" \
  -sS \
  https://${MASTODON_SERVER}/oauth/token | jq -r '.access_token'